# Generated by Django 5.0.7 on 2024-07-24 14:28

from django.db import migrations, models
from uuid import uuid4


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20240724_1705'),
    ]

    operations = [
            migrations.AlterField(
                model_name="Course",
                name="uuid",
                field=models.UUIDField(default=uuid4, unique=True),
            ),
        ]
