# Generated by Django 5.0.7 on 2024-07-24 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20240724_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='created',
            new_name='course_created',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='description',
            new_name='module_description',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='title',
            new_name='module_title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(help_text='описание курса', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(help_text='название курса', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='module_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_modules', to='courses.course'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=128)),
                ('task_description', models.TextField()),
                ('task_file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('task_module', models.ManyToManyField(related_name='module_task', to='courses.module')),
            ],
        ),
    ]
