# Generated by Django 5.0.7 on 2024-07-24 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_module',
        ),
        migrations.AddField(
            model_name='task',
            name='task_module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_task', to='courses.module'),
        ),
    ]
