# Generated by Django 5.0.7 on 2024-07-27 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_course', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_module', to='courses.module'),
        ),
    ]
