# Generated by Django 5.0.7 on 2024-07-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_module_module_course_alter_task_task_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='in_course',
            field=models.TextField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000002293F64A210>'),
        ),
        migrations.AddField(
            model_name='task',
            name='in_module',
            field=models.TextField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000002293F64A750>'),
        ),
    ]
