# Generated by Django 5.0.7 on 2024-07-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_module_in_course_task_in_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='in_course',
            field=models.TextField(default='51364175433416547257557'),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='module_course', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='task',
            name='in_module',
            field=models.TextField(default='76234256701043966702986'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='task_module', to='courses.module'),
        ),
    ]
