# Generated by Django 5.0.7 on 2024-07-27 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_module_in_course_alter_module_module_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
        migrations.RemoveField(
            model_name='task',
            name='notes',
        ),
        migrations.AlterField(
            model_name='module',
            name='in_course',
            field=models.CharField(default='66913498763224083713377', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='in_module',
            field=models.CharField(default='60496389799322773947966', max_length=30),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_task', models.CharField(default='39821813705166870540902', max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('notes', models.IntegerField(null=True)),
                ('solution_title', models.CharField(max_length=128)),
                ('task_file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('solution_description', models.TextField(blank=True)),
                ('solution_code', models.CharField(default='85868282145037628727066', max_length=30)),
                ('solution_for_task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='courses.task')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
