# Generated by Django 5.0.7 on 2024-07-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_task_email_remove_task_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='save_code',
            field=models.CharField(default='25144685818262651336662', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='module',
            name='in_course',
            field=models.CharField(default='25144685818262651336662', max_length=30),
        ),
        migrations.AlterField(
            model_name='solution',
            name='for_task',
            field=models.CharField(default='29135850305611985027304', max_length=30),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_code',
            field=models.CharField(default='24196350804901422783314', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='in_module',
            field=models.CharField(default='70036433934237249389407', max_length=30),
        ),
    ]
