# Generated by Django 5.0.7 on 2024-07-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_save_code_alter_module_in_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='save_code',
            field=models.CharField(default='94476137456906217396892', editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='in_course',
            field=models.CharField(default='94476137456906217396892', max_length=30),
        ),
        migrations.AlterField(
            model_name='solution',
            name='for_task',
            field=models.CharField(default='59213722370928292460304', max_length=30),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_code',
            field=models.CharField(default='39006845180496782908313', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='in_module',
            field=models.CharField(default='87370494658156004089843', max_length=30),
        ),
    ]
