# Generated by Django 5.0.7 on 2024-07-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_save_code_alter_module_in_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='save_code_module',
            field=models.CharField(default='3848986213013117560066', editable=False, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='save_code_task',
            field=models.CharField(default='83673917155215114717887', editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='save_code',
            field=models.CharField(default='19143423982069517863658', editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='in_course',
            field=models.CharField(default='19143423982069517863658', max_length=30),
        ),
        migrations.AlterField(
            model_name='solution',
            name='for_task',
            field=models.CharField(default='83673917155215114717887', max_length=30),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_code',
            field=models.CharField(default='8071375636571984050429', editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='in_module',
            field=models.CharField(default='3848986213013117560066', max_length=30),
        ),
    ]
