# Generated by Django 5.0.7 on 2024-07-28 08:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_module_save_code_module_task_save_code_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='save_code',
            field=models.CharField(default=uuid.UUID('5a61fc00-a3e7-48e0-a4fb-d7d374b05897'), editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='module',
            name='in_course',
            field=models.CharField(default=uuid.UUID('5a61fc00-a3e7-48e0-a4fb-d7d374b05897'), max_length=30),
        ),
        migrations.AlterField(
            model_name='module',
            name='save_code_module',
            field=models.CharField(default=uuid.UUID('c7c95480-6f59-4cdb-91b3-a74ee0934953'), editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='solution',
            name='for_task',
            field=models.CharField(default=uuid.UUID('1ba59d4b-1c5f-4494-8d94-d0c57058212d'), max_length=30),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_code',
            field=models.CharField(default='36849937103321461138296', editable=False, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='in_module',
            field=models.CharField(default=uuid.UUID('c7c95480-6f59-4cdb-91b3-a74ee0934953'), max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='save_code_task',
            field=models.CharField(default=uuid.UUID('1ba59d4b-1c5f-4494-8d94-d0c57058212d'), editable=False, max_length=60),
        ),
    ]
