# Generated by Django 5.0.7 on 2024-07-28 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_save_code_alter_module_in_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='save_code',
            field=models.CharField(default=uuid.UUID('c8289361-88e4-4275-8f3f-d4643cda947a'), editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='module',
            name='in_course',
            field=models.CharField(default=uuid.UUID('c8289361-88e4-4275-8f3f-d4643cda947a'), max_length=60),
        ),
        migrations.AlterField(
            model_name='module',
            name='save_code_module',
            field=models.CharField(default=uuid.UUID('69ffd213-8b59-4b64-bbe5-3e905077a36f'), editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='solution',
            name='for_task',
            field=models.CharField(default=uuid.UUID('ef5fd958-7c78-4ae7-aa16-298d71cee01c'), max_length=60),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_code',
            field=models.CharField(default='66438595413044169229673', editable=False, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='in_module',
            field=models.CharField(default=uuid.UUID('69ffd213-8b59-4b64-bbe5-3e905077a36f'), max_length=60),
        ),
        migrations.AlterField(
            model_name='task',
            name='save_code_task',
            field=models.CharField(default=uuid.UUID('ef5fd958-7c78-4ae7-aa16-298d71cee01c'), editable=False, max_length=60),
        ),
    ]
