# Generated by Django 5.0.7 on 2024-07-28 08:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_save_code_alter_module_in_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='save_code',
            field=models.CharField(default=uuid.UUID('af9867b7-a247-42bf-8ae9-13d35a28f333'), editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='module',
            name='in_course',
            field=models.CharField(default=uuid.UUID('af9867b7-a247-42bf-8ae9-13d35a28f333'), max_length=60),
        ),
        migrations.AlterField(
            model_name='module',
            name='save_code_module',
            field=models.CharField(default=uuid.UUID('4e07e734-7217-4c8f-b7a8-3baedd3650ce'), editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='solution',
            name='for_task',
            field=models.CharField(default=uuid.UUID('1ae401fd-03e0-4387-9265-e51c597235f5'), max_length=60),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_code',
            field=models.CharField(default='78409074930747460436286', editable=False, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='in_module',
            field=models.CharField(default=uuid.UUID('4e07e734-7217-4c8f-b7a8-3baedd3650ce'), max_length=60),
        ),
        migrations.AlterField(
            model_name='task',
            name='save_code_task',
            field=models.CharField(default=uuid.UUID('1ae401fd-03e0-4387-9265-e51c597235f5'), editable=False, max_length=60),
        ),
    ]
