# Generated by Django 5.0.7 on 2024-07-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_course_save_code_alter_module_in_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='save_code',
        ),
        migrations.RemoveField(
            model_name='module',
            name='in_course',
        ),
        migrations.RemoveField(
            model_name='module',
            name='save_code_module',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='for_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='in_module',
        ),
        migrations.RemoveField(
            model_name='task',
            name='save_code_task',
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_code',
            field=models.UUIDField(unique=True),
        ),
    ]
