# Generated by Django 5.0.7 on 2024-07-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_course_save_code_remove_module_in_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='teacher',
            field=models.CharField(default='<django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x0000017F6359DFD0>', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='teacher',
            field=models.CharField(default='<django.db.models.fields.related_descriptors.ForwardManyToOneDescriptor object at 0x0000017F6359DFD0>', max_length=30),
        ),
    ]
