# Generated by Django 5.0.7 on 2024-07-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_module_teacher_task_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='task',
            name='teacher',
        ),
    ]
