# Generated by Django 5.0.7 on 2024-07-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_remove_module_teacher_remove_task_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_description',
            field=models.TextField(default='описание отсутствует'),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_title',
            field=models.CharField(max_length=200),
        ),
    ]
