# Generated by Django 5.0.7 on 2024-07-28 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_module_module_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_course',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='module_course', to='courses.course'),
        ),
    ]
