# Generated by Django 5.0.7 on 2024-07-28 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_module_module_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_course', to='courses.course'),
        ),
    ]
