# Generated by Django 5.0.7 on 2024-07-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
