# Generated by Django 5.0.7 on 2024-07-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_task_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='courses.course'),
        ),
    ]
