# Generated by Django 5.0.7 on 2024-07-30 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_student_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='notes',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
