# Generated by Django 5.0.7 on 2024-07-30 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_task_task_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_code',
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='student',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solution',
            name='task_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
