# Generated by Django 5.0.7 on 2024-07-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_solution_solution_code_alter_solution_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='notation',
            field=models.TextField(blank=True),
        ),
    ]
